


package org.apache.kafka.connect.socket.legstar.bind;

import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolPackedDecimalBinding;
import java.math.BigDecimal;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.kafka.connect.socket.legstar.Dfhcommarea;
import org.apache.kafka.connect.socket.legstar.ObjectFactory;


/**
 * LegStar Binding for Complex element :
 *   Dfhcommarea.
 * 
 * This class was generated by LegStar Binding generator.
 */
public class DfhcommareaBinding 
             extends CComplexBinding {

    /** Value object to which this cobol complex element is bound. */
    private Dfhcommarea mValueObject;
  
    /** Indicates that the associated Value object just came from the constructor
     * and doesn't need to be recreated. */
    private boolean mUnusedValueObject = false;
    
    /** Maximum host bytes size for this complex object. */
    private static final int BYTE_LENGTH = 27;
    
    /** Child bound to value object property Dtar020KeycodeNo(String). */
    public ICobolStringBinding _dtar020KeycodeNo;
    /** Child bound to value object property Dtar020StoreNo(Short). */
    public ICobolPackedDecimalBinding _dtar020StoreNo;
    /** Child bound to value object property Dtar020Date(Integer). */
    public ICobolPackedDecimalBinding _dtar020Date;
    /** Child bound to value object property Dtar020DeptNo(Short). */
    public ICobolPackedDecimalBinding _dtar020DeptNo;
    /** Child bound to value object property Dtar020QtySold(Integer). */
    public ICobolPackedDecimalBinding _dtar020QtySold;
    /** Child bound to value object property Dtar020SalePrice(BigDecimal). */
    public ICobolPackedDecimalBinding _dtar020SalePrice;
            
    /** Logger. */
    private final Log _log = LogFactory.getLog(getClass());

    /** Binding factory. */
    private static final ICobolBindingFactory BF
        = CobolBindingFactory.getBindingFactory();
 
    /** Static reference to Value object factory to be used as default. */
    private static final ObjectFactory JF = new ObjectFactory();
    
    /** Current Value object factory (Defaults to the static one but can be
     *  changed). */
    private ObjectFactory mValueObjectFactory = JF;
    
    /**
     * Constructor for a root Complex element without a bound Value object.
     */
    public DfhcommareaBinding() {
        this(null);
    }

    /**
     * Constructor for a root Complex element with a bound Value object.
     * 
     * @param valueObject the concrete Value object instance bound to this
     *        complex element
     */
    public DfhcommareaBinding(
            final Dfhcommarea valueObject) {
        this("", "", null, valueObject);
    }

    /**
    * Constructor for a Complex element as a child of another element and
    * an associated Value object.
    * 
    * @param bindingName the identifier for this binding
    * @param fieldName field name in parent Value object
    * @param valueObject the concrete Value object instance bound to this
    *        complex element
    * @param parentBinding a reference to the parent binding
    */
    public DfhcommareaBinding(
            final String bindingName,
            final String fieldName,
            final ICobolComplexBinding parentBinding,
            final Dfhcommarea valueObject) {
        
        super(bindingName, fieldName, Dfhcommarea.class, null, parentBinding);
        mValueObject = valueObject;
        if (mValueObject != null) {
            mUnusedValueObject = true;
        }
        initChildren();
        setByteLength(BYTE_LENGTH);
    }

    /** Creates a binding property for each child. */
    private void initChildren() {
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing started");
        }
        /* Create binding children instances */

        _dtar020KeycodeNo = BF.createStringBinding("Dtar020KeycodeNo",
               "Dtar020KeycodeNo", String.class, this);
        _dtar020KeycodeNo.setCobolName("DTAR020-KEYCODE-NO");
        _dtar020KeycodeNo.setByteLength(8);
        _dtar020StoreNo = BF.createPackedDecimalBinding("Dtar020StoreNo",
               "Dtar020StoreNo", Short.class, this);
        _dtar020StoreNo.setCobolName("DTAR020-STORE-NO");
        _dtar020StoreNo.setByteLength(2);
        _dtar020StoreNo.setTotalDigits(3);
        _dtar020StoreNo.setIsSigned(true);
        _dtar020Date = BF.createPackedDecimalBinding("Dtar020Date",
               "Dtar020Date", Integer.class, this);
        _dtar020Date.setCobolName("DTAR020-DATE");
        _dtar020Date.setByteLength(4);
        _dtar020Date.setTotalDigits(7);
        _dtar020Date.setIsSigned(true);
        _dtar020DeptNo = BF.createPackedDecimalBinding("Dtar020DeptNo",
               "Dtar020DeptNo", Short.class, this);
        _dtar020DeptNo.setCobolName("DTAR020-DEPT-NO");
        _dtar020DeptNo.setByteLength(2);
        _dtar020DeptNo.setTotalDigits(3);
        _dtar020DeptNo.setIsSigned(true);
        _dtar020QtySold = BF.createPackedDecimalBinding("Dtar020QtySold",
               "Dtar020QtySold", Integer.class, this);
        _dtar020QtySold.setCobolName("DTAR020-QTY-SOLD");
        _dtar020QtySold.setByteLength(5);
        _dtar020QtySold.setTotalDigits(9);
        _dtar020QtySold.setIsSigned(true);
        _dtar020SalePrice = BF.createPackedDecimalBinding("Dtar020SalePrice",
               "Dtar020SalePrice", BigDecimal.class, this);
        _dtar020SalePrice.setCobolName("DTAR020-SALE-PRICE");
        _dtar020SalePrice.setByteLength(6);
        _dtar020SalePrice.setTotalDigits(11);
        _dtar020SalePrice.setFractionDigits(2);
        _dtar020SalePrice.setIsSigned(true);

        /* Add children to children list */
        getChildrenList().add(_dtar020KeycodeNo);
        getChildrenList().add(_dtar020StoreNo);
        getChildrenList().add(_dtar020Date);
        getChildrenList().add(_dtar020DeptNo);
        getChildrenList().add(_dtar020QtySold);
        getChildrenList().add(_dtar020SalePrice);
 
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing successful");
        }
    }
    
    /** {@inheritDoc} */
    public void createValueObject() throws HostException {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
        if (mUnusedValueObject && mValueObject != null) {
            mUnusedValueObject = false;
            return;
        }
        mValueObject = mValueObjectFactory.createDfhcommarea();
    }

    /** {@inheritDoc} */
    public void setChildrenValues() throws HostException {

         /* Make sure there is an associated Value object*/
        if (mValueObject == null) {
            createValueObject();
        }
        /* Get Value object property _dtar020KeycodeNo */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020KeycodeNo"
                    + " value=" + mValueObject.getDtar020KeycodeNo());
        }
        _dtar020KeycodeNo.setObjectValue(mValueObject.getDtar020KeycodeNo());
        /* Get Value object property _dtar020StoreNo */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020StoreNo"
                    + " value=" + mValueObject.getDtar020StoreNo());
        }
        _dtar020StoreNo.setObjectValue(mValueObject.getDtar020StoreNo());
        /* Get Value object property _dtar020Date */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020Date"
                    + " value=" + mValueObject.getDtar020Date());
        }
        _dtar020Date.setObjectValue(mValueObject.getDtar020Date());
        /* Get Value object property _dtar020DeptNo */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020DeptNo"
                    + " value=" + mValueObject.getDtar020DeptNo());
        }
        _dtar020DeptNo.setObjectValue(mValueObject.getDtar020DeptNo());
        /* Get Value object property _dtar020QtySold */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020QtySold"
                    + " value=" + mValueObject.getDtar020QtySold());
        }
        _dtar020QtySold.setObjectValue(mValueObject.getDtar020QtySold());
        /* Get Value object property _dtar020SalePrice */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_dtar020SalePrice"
                    + " value=" + mValueObject.getDtar020SalePrice());
        }
        _dtar020SalePrice.setObjectValue(mValueObject.getDtar020SalePrice());
     }

    /** {@inheritDoc} */
    public void setPropertyValue(final int index) throws HostException {
 
        ICobolBinding child = getChildrenList().get(index);
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
        if (!child.isBound()) {
            return;
        }
        
        /* Set the Value object property value from binding object */
        Object bindingValue = null;
        switch (index) {
        case 0:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setDtar020KeycodeNo((String) bindingValue);
            break;
        case 1:
            bindingValue = child.getObjectValue(Short.class);
            mValueObject.setDtar020StoreNo((Short) bindingValue);
            break;
        case 2:
            bindingValue = child.getObjectValue(Integer.class);
            mValueObject.setDtar020Date((Integer) bindingValue);
            break;
        case 3:
            bindingValue = child.getObjectValue(Short.class);
            mValueObject.setDtar020DeptNo((Short) bindingValue);
            break;
        case 4:
            bindingValue = child.getObjectValue(Integer.class);
            mValueObject.setDtar020QtySold((Integer) bindingValue);
            break;
        case 5:
            bindingValue = child.getObjectValue(BigDecimal.class);
            mValueObject.setDtar020SalePrice((BigDecimal) bindingValue);
            break;
         default:
            break;
        }
        if (_log.isDebugEnabled()) {
            _log.debug("Setting value of Value object property "
                    + child.getJaxbName()
                    + " value=" + bindingValue);
        }
    }

    /** {@inheritDoc} */
    public Object getObjectValue(
            final Class < ? > type) throws HostException {
        if (type.equals(Dfhcommarea.class)) {
            return mValueObject;
        } else {
            throw new HostException("Attempt to get binding " + getBindingName()
                    + " as an incompatible type " + type);
        }
    }

    /** {@inheritDoc} */
    public void setObjectValue(
            final Object bindingValue) throws HostException {
        if (bindingValue == null) {
            mValueObject = null;
            return;
        }
        if (bindingValue.getClass().equals(Dfhcommarea.class)) {
            mValueObject = (Dfhcommarea) bindingValue;
        } else {
            throw new HostException("Attempt to set binding " + getBindingName()
                    + " from an incompatible value " + bindingValue);
        }
    }

    /**
     * @return the java object factory for objects creation
     */
    public ObjectFactory getObjectFactory() {
        return mValueObjectFactory;
    }

    /**
     * @param valueObjectFactory the java object factory for objects creation 
     */
    public void setObjectFactory(final Object valueObjectFactory) {
        mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

    /** {@inheritDoc} */
    public boolean isSet() {
        return (mValueObject != null);
    }

    /**
     * @return the bound Value object
     */
    public Dfhcommarea getDfhcommarea() {
        return mValueObject;
    }
    
    /**
     * The COBOL complex element maximum length in bytes.
     * 
     * @return COBOL complex element maximum length in bytes
     */
    public int getByteLength() {
        return BYTE_LENGTH;
    }
}

